/* Copyright (C) 2023 Harry Clark */

/* SEGA Mega Drive Raspberry Pi Pico Interface */

/* THIS FILE PERTAINS TO THE MAIN FUNCTIONALITY OF THE CONTROLLER */
/* THE STATES IT WILL SHOW WHEN CONNECTING TO THE API AND PROVIDING */
/* FUNCTIONALITY FOR THE QUINTESENTIAL ASPECTS OF THE INTERFACE */

#ifndef MEGA_DRIVE_CONTROLLER
#define MEGA_DRIVE_CONTROLLER

/* NESTED INCLUDES */

#include "common.h"

#ifndef CONTROLLER_STATES
#define CONTROLLER_STATES

#define MEGA_DRIVE_DATA_PORT U32
#define MEGA_DRIVE_DATA_PORT_ADDR U32
#define MEGA_DIRVE_BUS_PORT U32
#define MEGA_DRIVE_BUS_PORT_ADDR U32

typedef struct MEGA_DEVICE
{
	typedef U32* GET_PORT(MEGA_DRIVE_DATA_PORT_ADDR());
};

#endif

#endif 