/* Copyright (C) 2023 Harry Clark */

/* SEGA Mega Drive Raspberry Pi Pico Interface */

/* THIS FILE PERTAINS TO THE MAIN FUNCTIONALITY OF THE CONTROLLER */
/* THE STATES IT WILL SHOW WHEN CONNECTING TO THE API AND PROVIDING */
/* FUNCTIONALITY FOR THE QUINTESENTIAL ASPECTS OF THE INTERFACE */

/* DOCUMENTATION USED: https://www.plutiedev.com/controllers */

#ifndef MEGA_DRIVE_CONTROLLER
#define MEGA_DRIVE_CONTROLLER

/* NESTED INCLUDES */

#include "common.h"

/* SYSTEM INCLUDES */

#include <assert.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdint.h>

#ifndef CONTROLLER_STATES
#define CONTROLLER_STATES

#define MEGA_DRIVE_DATA_PORT U32
#define MEGA_DRIVE_DATA_PORT_ADDR U32
#define MEGA_DIRVE_BUS_PORT U32
#define MEGA_DRIVE_BUS_PORT_ADDR U32
#define PLAYER_1_DATA_PORT 0xA10003
#define PLAYER_1_CONTROL_PORT 0xA10009
#define PLAYER_2_DATA_PORT 0xA10005
#define PLAYER_2_CONTROL_PORT 0xA1000B


#endif

typedef struct MEGA_DEVICE
{
	typedef U32* GET_PORT(MEGA_DRIVE_DATA_PORT_ADDR());
	typedef U32* GET_ADDRESS(MEGA_DIRVE_BUS_PORT, MEGA_DRIVE_DATA_PORT());
	typedef U32* GET_ATTACHED_DEVICE(MEGA_DRIVE_DATA_PORT());
	typedef U8* PLAYER_PORT;
	typedef MEGA_DEVICE* GET_DEVICE_TYPE();
};

typedef struct MEGA_DRIVE_PIN
{
	typedef U32* COUNT;
	typedef U8* PIN_1;
	typedef U8* PIN_2;
	typedef U8* PIN_3;
	typedef U8* PIN_4;
	typedef U8* PIN_5;
	typedef U8* PIN_6;
	typedef U8* PIN_7;
	typedef U8* PIN_8;
	typedef U8* PIN_9;
};

VOID_FUNCTION(MEGA_DRIVE_INIT);
VOID_FUNCTION(MEGA_DRIVE_PIN_SIGNAL);
VOID_FUNCTION(MEGA_DRIVE_NEXT_SIGNAL);
VOID_FUNCTION(MEGA_DRIVE_CONNECTED);
VOID_FUNCTION(MEGA_DRIVE_SET_PIN);
VOID_FUNCTION(MEGA_DRIVE_SET_INPUT);
VOID_FUNCTION(MEGA_DRIVE_UPDATE_INPUT);

#endif 
